version: 2.1
orbs:
  bullet_train_testing: gazayas/bullet_train_testing@dev:<<pipeline.git.revision>>
  # This may be different depending on the developer's Bullet Train app's needs.
  ruby: circleci/ruby@0.1.2
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

jobs:
  build:
    docker:
      - image: 'cimg/ruby:3.1-node'
    steps:
      - checkout
      - ruby/install:
          version: '3.1.1'
  command-tests:
    docker:
      - image: 'cimg/ruby:3.1-node'
    steps:
      - checkout
      - ruby/bundle-install
      - bullet_train_testing/standard_ruby
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - command-tests:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: gazayas/bullet_train_testing
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
